-- PDV Bosque — Postgres (Supabase). Execute no SQL Editor do projeto (uma vez por ambiente).

CREATE TABLE IF NOT EXISTS categories (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT UNIQUE NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  sort_order INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS items (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  category_id INTEGER NOT NULL REFERENCES categories(id),
  name TEXT NOT NULL,
  price DOUBLE PRECISION NOT NULL,
  description TEXT,
  requires_meat_point INTEGER DEFAULT 0,
  is_grill INTEGER DEFAULT 0,
  is_kitchen INTEGER DEFAULT 0,
  is_bar INTEGER DEFAULT 0,
  is_side INTEGER DEFAULT 0,
  is_prato_feito INTEGER DEFAULT 0,
  is_arvoredo INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS espetinhos_for_prato_feito (
  item_id INTEGER NOT NULL REFERENCES items(id) ON DELETE CASCADE,
  espetinho_id INTEGER NOT NULL REFERENCES items(id) ON DELETE CASCADE,
  PRIMARY KEY (item_id, espetinho_id)
);

CREATE TABLE IF NOT EXISTS waiters (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS comandas (
  id INTEGER PRIMARY KEY,
  mesa TEXT,
  status TEXT DEFAULT 'closed',
  waiter_id INTEGER REFERENCES waiters(id),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  closed_at TIMESTAMPTZ,
  people_count INTEGER DEFAULT 0,
  service_tax_percent DOUBLE PRECISION DEFAULT 0,
  couvert_per_person DOUBLE PRECISION DEFAULT 5,
  client_cpf TEXT,
  origin_order_id INTEGER,
  tipo_online TEXT,
  cliente_nome TEXT,
  cliente_telefone TEXT,
  cliente_email TEXT,
  endereco_rua TEXT,
  endereco_numero TEXT,
  endereco_complemento TEXT,
  endereco_bairro TEXT,
  endereco_referencia TEXT
);

CREATE TABLE IF NOT EXISTS pedidos (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  comanda_id INTEGER NOT NULL REFERENCES comandas(id) ON DELETE CASCADE,
  item_id INTEGER NOT NULL REFERENCES items(id),
  quantity INTEGER DEFAULT 1,
  unit_price DOUBLE PRECISION NOT NULL,
  observations TEXT,
  meat_point TEXT,
  caipirinha_base TEXT,
  caipirinha_picole INTEGER DEFAULT 0,
  dose_accompaniment TEXT,
  prato_feito_espetinho_id INTEGER REFERENCES items(id),
  status TEXT DEFAULT 'pending',
  sector TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS pedido_sector_status (
  pedido_id INTEGER NOT NULL REFERENCES pedidos(id) ON DELETE CASCADE,
  sector TEXT NOT NULL,
  status TEXT DEFAULT 'pending',
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (pedido_id, sector)
);

CREATE TABLE IF NOT EXISTS orders (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  tipo TEXT NOT NULL CHECK (tipo IN ('delivery', 'retirada')),
  status TEXT NOT NULL DEFAULT 'recebido' CHECK (status IN ('recebido', 'em_producao', 'pronto', 'saiu_entrega', 'entregue', 'cancelado')),
  cliente_nome TEXT NOT NULL,
  cliente_telefone TEXT NOT NULL,
  cliente_email TEXT,
  endereco_rua TEXT,
  endereco_numero TEXT,
  endereco_complemento TEXT,
  endereco_bairro TEXT,
  endereco_referencia TEXT,
  observacoes TEXT,
  valor_total DOUBLE PRECISION NOT NULL,
  comanda_id INTEGER REFERENCES comandas(id),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS order_items (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  item_id INTEGER NOT NULL REFERENCES items(id),
  quantity INTEGER NOT NULL DEFAULT 1,
  unit_price DOUBLE PRECISION NOT NULL,
  observations TEXT
);

CREATE INDEX IF NOT EXISTS idx_comandas_status ON comandas(status);
CREATE INDEX IF NOT EXISTS idx_pedidos_comanda ON pedidos(comanda_id);
CREATE INDEX IF NOT EXISTS idx_pedidos_status ON pedidos(status);
CREATE INDEX IF NOT EXISTS idx_pedidos_sector ON pedidos(sector);
CREATE INDEX IF NOT EXISTS idx_items_category ON items(category_id);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_comanda ON orders(comanda_id);
CREATE INDEX IF NOT EXISTS idx_order_items_order ON order_items(order_id);
